#!/usr/bin/env bash

# virtualenv_segment

# Set default symbols if not already defined in config
# Defaults should be standard symbols.
[[ -z ${PL_SYMBOLS[python]} ]] && PL_SYMBOLS[python]=$'\U1F40D\uFE0E'

# -----------------------------------------------------------------------------
# append to prompt: python virtual environment name
# arg: $1 foreground color
# arg; $2 background color
function virtualenv_segment {
    if [ -n "$VIRTUAL_ENV" ]; then
        local bg_color="$1"
        local fg_color="$2"
        local content=" ${PL_SYMBOLS[python]} "
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content" )"
        __last_color="$bg_color"
    fi
}

